# 1. 형변환

In [4]:
월급 = int(input("월급을 입력하세요:"))
연봉 = 월급 * 12
print(연봉)

월급을 입력하세요:100
1200

In [5]:
# 소수 -> 정수
f = 3.14159
number = int(f)
print(number)  # 출력: 3

3

In [6]:
# bool형
true_int = int(True)
false_int = int(False)

print(true_int)  # 출력: 1
print(false_int)  # 출력: 0

1
0

None은 int형으로 형변환 하면 0이라고 오해하는 분들이 많으신데 None은 int형으로 변환이 가능하지 않습니다.

여기서 주의해야 할 것은 int형은 str으로 변환했다가 다시 int형으로 변경하는 것이 문제가 되지 않지만 float형은 str으로 변환했다가 int형으로 변환했을 경우 error가 발생되게 됩니다. 닷(.)을 자동으로 인식해주지 않습니다.

In [7]:
print("bool('test'):", bool('test'))
print("bool(' '):", bool(' '))
print("bool(''):", bool(''))
print("bool(100):", bool(100))
print("bool(1):", bool(1))
print("bool(0):", bool(0))
print("bool(-1):", bool(-1))
print("bool(None):", bool(None))
print("bool([]):", bool([]))
print("bool(tuple()):", bool(tuple()))
print("bool({}):", bool({}))
print("bool(set()):", bool(set()))

bool('test'): True
bool(' '): True
bool(''): False
bool(100): True
bool(1): True
bool(0): False
bool(-1): True
bool(None): False
bool([]): False
bool(tuple()): False
bool({}): False
bool(set()): False

In [9]:
# 추가 사항
list(map(int, ['10', '20', '30'])) # 출력: [10, 20, 30]
list(map(int, '12345')) # 출력: [1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]

In [8]:
# 아래와 같이 문자열에 닷(.)이 포함되어 있으면 정수로 변환되지 않습니다.
x = 1.0
x = str(x)
print(int(x))

ValueError: ignored